[package]
name = "dbk64"
version = "0.0.1"
edition = "2021"

[dependencies]
dataview = "1.0.1"

[dependencies.windows]
version = "0.59.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
]
